### ISSUE TITLE
assert Model error

### ISSUE THREAD

**Issue by dejmail** [vinylproject/vinyl#1]
```
  File "/$HOME/venv/lib/python3.10/site-packages/vinyl/queryset.py", line 67, in __init__
    assert model
AssertionError
```
Hi there! Many thanks for putting in all the effort writing this library. I am trying to test it on the little Django project that I am busy with, but keep getting this AssertionError. Obvisouly the **model** is not making its way to the queryset __init__ method.  I have registered the custom manager as `vinyl = VinylManager()` under each model, and have registered the backend. I hope that I have done everything I need to, but as it is not working I'm sure something is missing or my understanding is lacking. Would you be able to shed any light? What is it that I am not understanding? Thanks!

**Comment by pwtail** [comment]
Hi @dejmail! I am sorry I forgot about this.

To test you currently have to call `init_models` signal after the models have been initialized. For example:

```python
from django.apps import AppConfig
from vinyl import init_models

class MyAppConfig(AppConfig):

  def ready(self):
    init_models.send(AppConfig)
```

The final way to do the init is yet to be found

**Comment by dejmail** [comment]
@pwtail Much appreciated. Created a pull request, as I think it is supposed to be `from vinyl.manager import init_models`.
