### ISSUE TITLE
Doesn't this always return True?

### ISSUE THREAD

**Issue by dvarrazzo** [vinylproject/vinyl#8]
https://github.com/vinylproject/vinyl/blob/4e0a7e1b4c30bb4a6887b4db59992961920f1ee7/vinyl/flags.py#L9

**Comment by pwtail** [comment]
No it doesn't. In the sync version hi_there is a regular function: https://github.com/vinylproject/vinyl/blob/4e0a7e1b4c30bb4a6887b4db59992961920f1ee7/vinyl_sync/vinyl/flags.py

**Comment by dvarrazzo** [comment]
How? It's kinda magic: doesn't it deserve a comment?

**Comment by pwtail** [comment]
the sync version is got from the async one by transpiling the code. Btw, I added a comment
