### ISSUE TITLE
Not all statements did execute

### ISSUE THREAD

**Issue by dejmail** [vinylproject/vinyl#9]
Hi there - I have been receiving this statement after attempting to write records to the DB i.e. "Not all statements did execute" from the deferred.py file. Would you be able to expand on that a bit ? Which statements exactly ? Are some of the records that should have been written to the DB not being written ?

Thanks

**Comment by pwtail** [comment]
That definetely means you are using an old version. vinyl changed a bit and now btw  has both sync and async versions.

This message was related to deferred statements. In case when we don't need to fetch the result of the statements, we collect them in a list and then execute at the end. The message means not all of them did execute

**Comment by dejmail** [comment]
Ok thanks. I'll update to the version on Github.
